#!/usr/bin/env bash
# gen-commands.sh — emit native command adapters from os/commands.md.
#
# Usage: os/scripts/gen-commands.sh          regenerate both adapter sets
#        os/scripts/gen-commands.sh --check  exit 1 (writing nothing) if adapters drift
#
# os/commands.md is the single source. Per "## <name>" block it emits:
#   .claude/commands/<name>.md        Claude Code slash command
#   .agents/skills/<name>/SKILL.md    portable agent skill
# Only files this script generated itself (they carry a GENERATED marker) are
# ever created, overwritten, or removed; anything else in those two
# directories — a hand-added command or skill with no marker — is left alone,
# regen or no regen (PF-017).
# README.md's command table is stamped between COMMANDS:BEGIN/END markers from
# the same records (skipped when the markers are absent) — no copy can drift.
# The manifest is validated first: every block complete, names unique,
# playbooks real — a half-written block is an error, never a silent skip.
# Parsing uses awk/sed only. Never edit the adapters by hand — edit the
# manifest and rerun this script.

set -eu
if (set -o pipefail) 2>/dev/null; then set -o pipefail; fi
LC_ALL=C
export LC_ALL

case "${1:-}" in
  ""|--check) ;;
  *) echo "usage: os/scripts/gen-commands.sh [--check]" >&2; exit 2 ;;
esac

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "$ROOT"

MANIFEST=os/commands.md
if [ ! -f "$MANIFEST" ]; then
  echo "ERROR: $MANIFEST not found" >&2
  exit 1
fi

TMP=$(mktemp -d "${TMPDIR:-/tmp}/gen-commands.XXXXXX")
cleanup() {
  rm -rf "$TMP" ".README.md.$$"
  # Stray per-file temps from a crash mid-write (this process's PID only —
  # never touches another run's in-flight temps).
  find .claude/commands .agents/skills -maxdepth 2 -name ".*.$$" -exec rm -f {} + 2>/dev/null || :
}
trap cleanup EXIT

# Every file this script writes carries this marker (PF-017): only a file
# that already carries it is ever auto-removed when its name drops out of
# the manifest. Anything else sitting in .claude/commands/ or
# .agents/skills/ — a user's own custom command or skill — was never ours
# to touch and survives regen untouched.
MARK='<!-- GENERATED by os/scripts/gen-commands.sh — do not hand-edit. Edit os/commands.md and rerun. -->'

# Manifest -> TAB-separated records: name<TAB>desc<TAB>playbook.
# Prefix widths: "## " = 3, "- desc: " = 8, "- playbook: " = 12.
awk '
  /^## /          { name = substr($0, 4);  sub(/[[:space:]]+$/, "", name); desc = "" }
  /^- desc: /     { desc = substr($0, 9);  sub(/[[:space:]]+$/, "", desc) }
  /^- playbook: / { pb   = substr($0, 13); sub(/[[:space:]]+$/, "", pb)
                    if (name != "" && desc != "" && pb != "") {
                      printf "%s\t%s\t%s\n", name, desc, pb
                    }
                    name = "" }
' "$MANIFEST" > "$TMP/records"

# Validate before touching anything: a malformed block must fail loudly, not
# silently drop that command's adapters.
H=$(grep -cE '^## ' "$MANIFEST" || true)
R=$(wc -l < "$TMP/records"); R=$((R))
if [ "$R" -ne "$H" ]; then
  echo "ERROR: $MANIFEST has $H '## <name>' block(s) but only $R complete — each needs '- desc:' and '- playbook:'" >&2
  exit 1
fi
if cut -f1 "$TMP/records" | sort | uniq -d | grep -q .; then
  echo "ERROR: duplicate command names in $MANIFEST:" >&2
  cut -f1 "$TMP/records" | sort | uniq -d >&2
  exit 1
fi
cut -f1 "$TMP/records" > "$TMP/names"

mkdir -p "$TMP/claude" "$TMP/skills"

TAB=$(printf '\t')
N=0
while IFS="$TAB" read -r name desc pb; do
  case $name in
    ""|*[!a-z0-9-]*)
      echo "ERROR: bad command name '$name' in $MANIFEST (want [a-z0-9-])" >&2
      exit 1 ;;
  esac
  if [ ! -f "$pb" ]; then
    echo "ERROR: command '$name' references missing playbook '$pb'" >&2
    exit 1
  fi
  {
    printf -- '---\ndescription: %s\n---\n\n' "$desc"
    printf 'Follow the playbook at %s. It is the single source of truth for this procedure.\n' "$pb"
    printf '\n%s\n' "$MARK"
  } > "$TMP/claude/$name.md"
  mkdir "$TMP/skills/$name"
  {
    printf -- '---\nname: %s\ndescription: %s\n---\n\n' "$name" "$desc"
    printf 'Follow the playbook at %s. It is the single source of truth for this procedure.\n' "$pb"
    printf '\n%s\n' "$MARK"
  } > "$TMP/skills/$name/SKILL.md"
  N=$((N + 1))
done < "$TMP/records"

if [ "$N" -eq 0 ]; then
  echo "ERROR: no complete command blocks parsed from $MANIFEST" >&2
  exit 1
fi

# README table: regenerate between the COMMANDS markers from the same records.
have_markers=0
if [ -f README.md ] && grep -qF 'COMMANDS:BEGIN' README.md && grep -qF 'COMMANDS:END' README.md; then
  have_markers=1
  {
    printf '| Command | Playbook | What it does |\n'
    printf '|---------|----------|--------------|\n'
    while IFS="$TAB" read -r name desc pb; do
      printf '| `/%s` | `%s` | %s |\n' "$name" "$pb" "$desc"
    done < "$TMP/records"
  } > "$TMP/table"
  awk -v tf="$TMP/table" '
    /COMMANDS:BEGIN/ { print; while ((getline line < tf) > 0) print line; inside = 1; next }
    /COMMANDS:END/   { inside = 0 }
    !inside { print }
  ' README.md > "$TMP/README.new"
fi

# Adapters we generated ourselves (carry MARK) whose name has dropped out of
# the current manifest — genuine stale adapters, safe to remove. Anything
# without MARK is left out of both lists no matter its name: it was never
# ours (PF-017).
stale_claude() {
  [ -d .claude/commands ] || return 0
  for f in .claude/commands/*.md; do
    [ -e "$f" ] || continue
    n=$(basename "$f" .md)
    if grep -qF "$MARK" "$f" 2>/dev/null && ! grep -qxF "$n" "$TMP/names"; then
      printf '%s\n' "$f"
    fi
  done
}
stale_skills() {
  [ -d .agents/skills ] || return 0
  for d in .agents/skills/*/; do
    [ -d "$d" ] || continue
    d=${d%/}
    n=$(basename "$d")
    if grep -qF "$MARK" "$d/SKILL.md" 2>/dev/null && ! grep -qxF "$n" "$TMP/names"; then
      printf '%s\n' "$d"
    fi
  done
}

if [ "${1:-}" = "--check" ]; then
  DRIFT=0
  while IFS="$TAB" read -r name desc pb; do
    cf=".claude/commands/$name.md"
    if [ ! -f "$cf" ]; then
      echo "DRIFT: $cf is missing"
      DRIFT=1
    elif ! diff -u "$cf" "$TMP/claude/$name.md" > "$TMP/diff" 2>&1; then
      echo "DRIFT: $cf does not match $MANIFEST:"
      cat "$TMP/diff"
      DRIFT=1
    fi
    sf=".agents/skills/$name/SKILL.md"
    if [ ! -f "$sf" ]; then
      echo "DRIFT: $sf is missing"
      DRIFT=1
    elif ! diff -u "$sf" "$TMP/skills/$name/SKILL.md" > "$TMP/diff" 2>&1; then
      echo "DRIFT: $sf does not match $MANIFEST:"
      cat "$TMP/diff"
      DRIFT=1
    fi
  done < "$TMP/records"
  sc=$(stale_claude)
  if [ -n "$sc" ]; then
    echo "DRIFT: stale generated command file(s) no longer in $MANIFEST (regen removes only these):"
    printf '%s\n' "$sc" | sed 's/^/  /'
    DRIFT=1
  fi
  ss=$(stale_skills)
  if [ -n "$ss" ]; then
    echo "DRIFT: stale generated skill dir(s) no longer in $MANIFEST (regen removes only these):"
    printf '%s\n' "$ss" | sed 's/^/  /'
    DRIFT=1
  fi
  if [ "$have_markers" -eq 1 ] && ! diff -u README.md "$TMP/README.new" > "$TMP/rdiff"; then
    echo "DRIFT: README.md command table does not match $MANIFEST:"
    cat "$TMP/rdiff"
    DRIFT=1
  fi
  if [ "$DRIFT" -ne 0 ]; then
    echo "Run os/scripts/gen-commands.sh to regenerate."
    exit 1
  fi
  echo "OK: adapters are current ($N command(s))"
else
  mkdir -p .claude/commands .agents/skills
  sc=$(stale_claude)
  if [ -n "$sc" ]; then printf '%s\n' "$sc" | while IFS= read -r f; do rm -f "$f"; done; fi
  ss=$(stale_skills)
  if [ -n "$ss" ]; then printf '%s\n' "$ss" | while IFS= read -r d; do rm -rf "$d"; done; fi
  while IFS="$TAB" read -r name desc pb; do
    cnew=".claude/commands/.$name.md.$$"
    cp "$TMP/claude/$name.md" "$cnew"
    mv "$cnew" ".claude/commands/$name.md"
    mkdir -p ".agents/skills/$name"
    snew=".agents/skills/$name/.SKILL.md.$$"
    cp "$TMP/skills/$name/SKILL.md" "$snew"
    mv "$snew" ".agents/skills/$name/SKILL.md"
  done < "$TMP/records"
  if [ "$have_markers" -eq 1 ]; then
    NEWR=".README.md.$$"
    cp "$TMP/README.new" "$NEWR"
    mv "$NEWR" README.md
  fi
  echo "OK: $N command adapter(s) generated (.claude/commands, .agents/skills); unmanaged files left untouched"
fi
